version: '3'

networks:
  app-tier:
    driver: bridge

services:
  todo:
    build: .
    networks:
      - app-tier
    ports:
      - "8010:8010"
    depends_on:
      - postgres
    volumes:
      - "./todo/src/app/"
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - app-tier